namespace: hw4-optional-dev-both

resources:
- https://github.com/drsylent/cubix-cloudnativev2-block4-optional//base?ref=main
- ingress.yaml

components:
- https://github.com/drsylent/cubix-cloudnativev2-block4-optional//components/frontapp?ref=main
- ../../components/backapp-service
- ../../components/frontapp-service
- ../../components/backapp-env-configured
- ../../components/frontapp-env-configured
