namespace: hw4-optional-test-backapp

resources:
- https://github.com/drsylent/cubix-cloudnativev2-block4-optional//base?ref=main
- ingress.yaml

components:
- ../../components/backapp-service

patches:
- path: patch-backapp-message.yaml
