namespace: hw4-optional-dev-backapp

resources:
- https://github.com/drsylent/cubix-cloudnativev2-block4-optional//base?ref=main
- ingress.yaml

components:
- ../../components/backapp-service
- ../../components/backapp-env-configured
